
function onInit()
	-- Used to auto populate skills before the skills tab has been opened.
	--Debug.console("charsheet_init.lua: onInit");
	local skillsnode = window.getDatabaseNode().createChild("skills");
	if skillsnode then
		local skillautocreated = skillsnode.createChild("..skillsautogenerated", "number");
		if skillautocreated.getValue() ~= 1 then
			Debug.console("charsheet_init.lua: Skills haven't been created - creating...");
			for k,v in pairs(DataCommon.basicskilldata) do
				-- Build Specialities if any			
				if v.specialities then
					for k2,v2 in pairs(v.specialities) do
						local skillnode = skillsnode.createChild();
						
						skillnode.createChild("name","string").setValue(k .. " ("..k2..") ");
						skillnode.createChild("description","formattedtext").setValue(v.description .. v2.description);		
						skillnode.createChild("canaddspecialities","number").setValue(v.canaddspecialities);
						skillnode.createChild("characteristic","string").setValue("-");
						
					end		
				else
					local skillnode = skillsnode.createChild();
					skillnode.createChild("name","string").setValue(k);
					skillnode.createChild("description","formattedtext").setValue(v.description);
					skillnode.createChild("canaddspecialities","number").setValue(v.canaddspecialities);
					skillnode.createChild("characteristic","string").setValue("-");
				end
				
			end
			skillsnode.getChild("..skillsautogenerated").setValue(1);
		else
			Debug.console("charsheet_init.lua: Skills already created.");
		end
	end	
end
